# Generated by Django 5.2.5 on 2025-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='user_type',
            field=models.TextField(choices=[('PUB', 'publisher'), ('SUB', 'viewer')], default=('SUB', 'viewer'), max_length=20),
        ),
    ]
