# Generated by Django 5.2.5 on 2025-08-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_app_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_users',
            name='is_publisher',
        ),
        migrations.AlterField(
            model_name='app_users',
            name='user_type',
            field=models.TextField(choices=[('PUB', 'publisher'), ('SUB', 'viewer'), ('NaN', 'NO-ACTIVE')], default=('SUB', 'viewer'), max_length=20),
        ),
    ]
