# Generated by Django 5.2.5 on 2025-08-07 11:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='publish at')),
                ('contract_type', models.CharField(choices=[('invest', 'Investments'), ('sale', 'Sales'), ('rent', 'Rental')], max_length=20)),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('apartment', 'Apartment'), ('house', 'House'), ('hut', 'Hut')], max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractPropertyContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.contract')),
                ('num_bedrooms', models.IntegerField(default=1)),
                ('num_bathrooms', models.IntegerField(default=1)),
            ],
            bases=('deal.contract',),
        ),
        migrations.CreateModel(
            name='HutContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.contract')),
                ('is_rural', models.BooleanField(default=False, help_text='Indicates if hut is in a rural area')),
            ],
            bases=('deal.contract',),
        ),
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deal.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('c', 'Completed'), ('p', 'Pending'), ('i', 'Incomplete'), ('x', 'Closed')], default='p', max_length=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deal.contract')),
                ('contract_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_owned', to=settings.AUTH_USER_MODEL)),
                ('witness_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness_1', to=settings.AUTH_USER_MODEL)),
                ('witness_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='closed_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_contracts', to='deal.deal'),
        ),
        migrations.CreateModel(
            name='DealComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deal.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentContract',
            fields=[
                ('abstractpropertycontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.abstractpropertycontract')),
                ('floor_number', models.IntegerField()),
                ('has_parking', models.BooleanField(default=False)),
            ],
            bases=('deal.abstractpropertycontract',),
        ),
        migrations.CreateModel(
            name='HouseContract',
            fields=[
                ('abstractpropertycontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.abstractpropertycontract')),
                ('has_garden', models.BooleanField(default=False)),
            ],
            bases=('deal.abstractpropertycontract',),
        ),
        migrations.CreateModel(
            name='LandContract',
            fields=[
                ('abstractpropertycontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deal.abstractpropertycontract')),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Size of the land in square meters', max_digits=10)),
                ('is_agricultural', models.BooleanField(default=False, help_text='Indicates if land is agricultural')),
            ],
            bases=('deal.abstractpropertycontract',),
        ),
    ]
